import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalJson } from "../src/core/canonical.mjs";
import { checksum } from "../src/core/checksum.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function normalizeBody(value) {
  return `${value.replaceAll("\r\n", "\n").trim()}\n`;
}

function yamlString(value) {
  return JSON.stringify(value);
}

export const SKILL_TRACKS = Object.freeze(["pipeline", "audit"]);

export function validateSkillManifest(manifest) {
  if (manifest?.schema_version !== 1 || !Array.isArray(manifest.skills)) {
    throw new TypeError("skills/manifest.json is invalid");
  }
  const identifiers = new Set();
  for (const skill of manifest.skills) {
    if (!/^[a-z][a-z0-9-]{1,47}$/.test(skill.id) || typeof skill.description !== "string") {
      throw new TypeError("Every declared skill requires a valid id and description");
    }
    if (identifiers.has(skill.id)) throw new TypeError(`Duplicate skill id: ${skill.id}`);
    identifiers.add(skill.id);
    if (!SKILL_TRACKS.includes(skill.track)) {
      throw new TypeError(`${skill.id}: track must be one of ${SKILL_TRACKS.join(", ")}`);
    }
    if (!Array.isArray(skill.requires)) throw new TypeError(`${skill.id}: requires must be an array`);
    if (skill.track === "audit" && skill.requires.length > 0) {
      throw new TypeError(`${skill.id}: an audit skill cannot declare prerequisites`);
    }
  }
  for (const skill of manifest.skills) {
    for (const prerequisite of skill.requires) {
      if (!identifiers.has(prerequisite)) {
        throw new TypeError(`${skill.id}: unknown prerequisite ${prerequisite}`);
      }
    }
  }
  pipelinePositions(manifest.skills);
  return manifest;
}

async function loadManifest() {
  return validateSkillManifest(
    JSON.parse(await readFile(path.join(root, "skills", "manifest.json"), "utf8")),
  );
}

function pipelinePositions(skills) {
  const pipeline = skills.filter((skill) => skill.track === "pipeline");
  const byId = new Map(pipeline.map((skill) => [skill.id, skill]));
  const positions = new Map();
  const visit = (skill, seen) => {
    if (positions.has(skill.id)) return positions.get(skill.id);
    if (seen.has(skill.id)) throw new TypeError(`Cyclic skill prerequisite at ${skill.id}`);
    seen.add(skill.id);
    const depth = Math.max(
      0,
      ...skill.requires.filter((id) => byId.has(id)).map((id) => visit(byId.get(id), seen)),
    );
    positions.set(skill.id, depth + 1);
    return depth + 1;
  };
  for (const skill of pipeline) visit(skill, new Set());
  return positions;
}

function sequencedDescription(skill, { positions, invocationName }) {
  if (skill.track !== "pipeline") {
    return `Independent audit that runs against an authorized target environment and needs no plan. ${skill.description}`;
  }
  const prefix = `Step ${positions.get(skill.id)} of ${positions.size} in the QA pipeline`;
  const prerequisites = skill.requires.map(invocationName).join(" and ");
  return prerequisites.length === 0
    ? `${prefix}, and its entry point. ${skill.description}`
    : `${prefix}; requires a completed ${prerequisites} run. ${skill.description}`;
}

function indexDocument(skills, { positions, invocationName, skillsPath }) {
  const pipeline = skills
    .filter((skill) => skill.track === "pipeline")
    .sort((left, right) => positions.get(left.id) - positions.get(right.id))
    .map((skill) => `${positions.get(skill.id)}. \`${invocationName(skill.id)}\` - ${skill.description}`);
  const audits = skills
    .filter((skill) => skill.track === "audit")
    .map((skill) => `- \`${invocationName(skill.id)}\` - ${skill.description}`);
  return [
    "# Holistic QA skills",
    "",
    `Generated by \`holistic-qa install\`. The skills live in \`${skillsPath}\`; re-run the install command to update them.`,
    "",
    "## Pipeline, in order",
    "",
    "Each step consumes the checksum-valid run the previous step produced, so run them in sequence.",
    "",
    ...pipeline,
    "",
    "## Independent audits",
    "",
    "These need an authorized target environment rather than a plan, and can run in any order, before or after the pipeline.",
    "",
    ...audits,
    "",
    "## What every skill returns",
    "",
    "Durable artifacts under `qa/runs/<run-id>/` with a checksummed artifact index and a shared return envelope, plus raw evidence under `test-results/<run-id>/`. A skill returns `completed` only when its declared scope is covered and every required artifact validates; otherwise `partial`, `blocked`, or `failed` with the uncovered scope named.",
    "",
  ].join("\n");
}

async function buildLayout(outputRoot, { provider, providerRoot, frontmatterName }) {
  const sourceManifest = await loadManifest();
  const providerDirectory = path.join(outputRoot, providerRoot);
  const positions = pipelinePositions(sourceManifest.skills);
  const generated = [];
  for (const skill of sourceManifest.skills) {
    const sourcePath = path.join(root, "skills", "holistic-qa", skill.id, "instructions.md");
    const body = normalizeBody(await readFile(sourcePath, "utf8"));
    const bodyChecksum = checksum(body);
    const directory = path.join(providerDirectory, "skills", `holistic-qa-${skill.id}`);
    await mkdir(directory, { recursive: true });
    const document = [
      "---",
      `name: ${frontmatterName(skill.id)}`,
      `description: ${yamlString(sequencedDescription(skill, { positions, invocationName: frontmatterName }))}`,
      "metadata:",
      `  provider: ${provider}`,
      `  source_checksum: ${bodyChecksum}`,
      `  track: ${skill.track}`,
      ...(skill.requires.length === 0
        ? []
        : [`  requires: ${yamlString(skill.requires.map(frontmatterName).join(", "))}`]),
      "---",
      "",
      body,
    ].join("\n");
    await writeFile(path.join(directory, "SKILL.md"), document, "utf8");
    generated.push({ id: skill.id, source_checksum: bodyChecksum, track: skill.track, requires: skill.requires });
  }
  const adapterManifest = {
    schema_version: 1,
    provider,
    skills: generated.sort((left, right) => left.id.localeCompare(right.id)),
  };
  // Nested under providerRoot (not outputRoot) so installing both providers into one
  // target directory - e.g. a consuming project's own repo root - never collides.
  await mkdir(providerDirectory, { recursive: true });
  await writeFile(
    path.join(providerDirectory, ".holistic-qa-manifest.json"),
    `${canonicalJson(adapterManifest)}\n`,
    "utf8",
  );
  await writeFile(
    path.join(providerDirectory, "holistic-qa-README.md"),
    indexDocument(sourceManifest.skills, {
      positions,
      invocationName: frontmatterName,
      skillsPath: `${providerRoot}/skills/`,
    }),
    "utf8",
  );
  return adapterManifest;
}

async function buildCodex(outputRoot) {
  return buildLayout(outputRoot, {
    provider: "codex",
    providerRoot: ".agents",
    frontmatterName: (id) => `holistic-qa:${id}`,
  });
}

async function buildClaude(outputRoot) {
  return buildLayout(outputRoot, {
    provider: "claude",
    providerRoot: ".claude",
    frontmatterName: (id) => `holistic-qa-${id}`,
  });
}

const PROVIDERS = Object.freeze({ codex: buildCodex, claude: buildClaude });

export async function buildAdapter(provider, outputRoot) {
  const builder = PROVIDERS[provider];
  if (!builder) throw new TypeError(`Unsupported v1 provider: ${provider}`);
  return builder(outputRoot);
}

async function run() {
  const [provider, option] = process.argv.slice(2);
  if (!provider) throw new TypeError("Provider is required");
  const check = option === "--check";
  const outputRoot = check
    ? await mkdtemp(path.join(os.tmpdir(), `holistic-qa-${provider}-`))
    : path.join(root, "dist", provider);
  try {
    const result = await buildAdapter(provider, outputRoot);
    process.stdout.write(`${canonicalJson({ output: outputRoot, ...result })}\n`);
  } finally {
    if (check) await rm(outputRoot, { recursive: true, force: true });
  }
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  run().catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
